/**
 * @litter/nitro — the NitroLitter native module + its Iroh-backed Transport.
 *
 * `getNitroLitter()` resolves the registered HybridObject at runtime. The native
 * impl is generated by nitrogen + a Swift/Kotlin `HybridNitroLitter` that links
 * the embedded Iroh client. Until the native side is built, importing the module
 * throws — the app falls back to HttpTransport (see apps/mobile services).
 */

import { NitroModules } from "react-native-nitro-modules";
import type { NitroLitter } from "./NitroLitter.nitro";

export type { NitroLitter } from "./NitroLitter.nitro";
export { IrohTransport } from "./irohTransport";

let cached: NitroLitter | null = null;

export function getNitroLitter(): NitroLitter {
  if (!cached) {
    cached = NitroModules.createHybridObject<NitroLitter>("NitroLitter");
  }
  return cached;
}

/** True if the native module is linked & available on this build. */
export function isNitroLitterAvailable(): boolean {
  try {
    getNitroLitter();
    return true;
  } catch {
    return false;
  }
}
